[tool.poetry]
name = "goit-ds-hw-02"
version = "0.1.0"
description = ""
authors = ["Maksym Sydorenko <maksym.sy96@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
faker = "^33.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
